### ISSUE TITLE
KAVA on Ledger shows zero and I can't claim rewards

### ISSUE THREAD

**Issue by jkq2010** [chainapsis/keplr-extension#40] opened 2020-11-06 00:29 UTC
I am staking KAVA with stakefish via Lunie. Lunie is closing down so I have migrated from my Ledger over to Keplr. My Lunie account shows my KAVA balance at 3460.76 with 0.9 to claim but my KEPLR account shows no KAVA tokens. I also cant seem to unstake from my stakefish or claim my rewards.
![Screenshot 2020-11-06 000150](https://user-images.githubusercontent.com/25287198/98311387-2aaf0c00-1fc7-11eb-93a6-f2c66a422e62.jpg)
KR

**Comment by Thunnini** [comment] 2020-11-06 09:22
It looks like this is because your account is a vesting account, which is not supported on Keplr at this time. We’ll get this resolved in the coming weeks.

**Comment by jkq2010** [comment] 2020-11-06 20:52
Thanks for your advice!

**Comment by Thunnini** [comment] 2020-11-12 10:29
I fixed parsing a vesting account without regarding the vesting/vested amount. This fix has been published to v0.7.1. Let me know that the issue is resolved.

**Closed** 2020-11-16 09:07 UTC
