### ISSUE TITLE
Wallet loses focus and state if clicking away (e.g. copy/paste address/memo)

### ISSUE THREAD

**Issue by cryptotester** [chainapsis/keplr-extension#67] opened 2021-03-02 08:26 UTC
Steps to reproduce:

- Copy a secret address where to deposit some coins (e.g. your address in binance)
- Click the keplr extension
- Click Send
- Paste the address
- Go to your notes or website and copy the MEMO
- Click again to the keplr extension

**Result:**

I see the initial keplr screen showing my total balance and send / deposit buttons.

**Expected result:**

I was expecting to see the screen I was filling a few seconds before, to paste the memo and complete the transaction.

Like this it's unusable, if I can't even paste a memo after pasting an address it's very dangerous. I already lost funds in the past by manually writing a memo instead of copy/pasting it and I don't want to risk again the same kind of loss.

**MetaMask** solves this problem by having an "expand" button, which opens metamask in a fullscreen tab. If you could do the same it would be awesome.

**Possible fix 1**: **remember the last state**, if somebody was pasting an address, leave that screen so the user comes back and can continue the transaction by pasting memo, pasting amount etc.

**Possible fix 2**: Check the **Terra Station extension** (for the mirror protocol) I reported the same issue and they just fixed it by allowing to right click on "Terra Station" at the top once the popup is open to "open in a new tab". They didn't even make a design for the full screen, it's the same size. I guess it was the fastest fix.

Since possible fix 1 needs more work, maybe possible fix 2 is the easiest fastest way to fix this (I still believe do it like MetaMask would be the best and most elegant solution).

Thank you.

**Comment by cryptotester** [comment] 2021-08-20 11:16
Guys PLEASE fix this, it's not just an "anhancement". I mean you even grayed out "Options" if I right click on keplr from my chrome extensions. Other extensions at least allow a user to right click on options and open a new tab, then rename options.html to app.html.

But guys come on just add a button somewhere at the top to simply open keplr in a new tab.

I reported exactly this same issue for terra station and they added the button.
I reported this to xdefi wallet, they added the button.

I'm not asking the moon, just to open this extension in a new tab, should be like 10 minutes of work...

User story: try to go to secret network > tokens list > add a new token > try to import an existing key. You paste the key you copied from another window, now you still need to paste also the token address... you go to another window to copy the token address, you go back to keplr and BOOM it lost focus and you can't paste it.

Just this simple scenario shows you how important is to allow to open keplr in a new tab.

Thank you

**Comment by delivan** [comment] 2021-11-26 09:15
Hi @cryptotester

we fixed it by adding the detach button to the top right of send page. This fix has been published to v0.9.6. Let me know that the issue is resolved. thank you for reporting.

**Closed by delivan** 2021-11-26 09:15 UTC
Labels: enhancement

**Comment by cryptotester** [comment] 2022-05-09 12:42
> Hi @cryptotester
> 
> we fixed it by adding the detach button to the top right of send page. This fix has been published to v0.9.6. Let me know that the issue is resolved. thank you for reporting.

Hi, thank you, but it's still buggy. Try e.g. the following:

- switch to secret network
- settings (top left button)
- add token
- (advanced) import my own viewing key
- try to copy the token address and paste it at the top (works only if the address is already in the clipboard, else it will lose focus)
- try to paste the viewing key (won't work if you go somewhere else, e.g. to copy it from a passwords database or text file).

Please can you make a more generic solution as I suggested? Simply allow to use the extension in a new tab (like metamask, terra station, xdefi etc.).

Else you can try to fix this issue, but who knows, maybe in the future another similar issue will appear and will require extra work...

Thank you

**Comment by cryptotester** [comment] 2022-05-11 21:28
@delivan can you please consider to re-open this? (read my comment above)
